// <autogenerated />
#nullable enable
using System;
using System.Collections.Generic;

namespace UseDeptorygen.Samples.AbstractClass
{
	internal partial class Factory : IFactory
		, IDisposable
	{
		private ServiceSilver? _ResolveServiceCache;

		public Factory()
		{
		}

		public ServiceBase ResolveService()
		{
			return _ResolveServiceCache ??= new ServiceSilver();
		}

		public void Dispose()
		{
		}
	}
}