// <autogenerated />
#nullable enable
using System;
using System.Collections.Generic;

namespace Deptorygen.XUnit.DataSource.UnitTests.ResolverDelegation.Source
{
	internal partial class Factory : IFactory
		, IDisposable
	{
		private Service? _ResolveServiceCache;

		public Factory()
		{
		}

		public Service ResolveService()
		{
			return _ResolveServiceCache ??= new Service();
		}

		public IServiceApi ResolveServiceApi()
		{
			return ResolveService();
		}

		public void Dispose()
		{
		}
	}
}