// <autogenerated />
#nullable enable
using System;
using System.Collections.Generic;

namespace UseDeptorygen.Samples.CaptureMixin
{
	internal partial class BaseFactory : IBaseFactory
		, IDisposable
	{
		private Service? _ResolveServiceCache;
		private CaptureFactory? _ResolveCaptureFactoryCache;

		public BaseFactory()
		{
		}

		public Service ResolveService()
		{
			return _ResolveServiceCache ??= new Service();
		}

		public ICaptureFactory ResolveCaptureFactory()
		{
			return _ResolveCaptureFactoryCache ??= new CaptureFactory(this);
		}

		public void Dispose()
		{
			_ResolveCaptureFactoryCache?.Dispose();
		}
	}
}