// <autogenerated />
#nullable enable
using System;
using System.Collections.Generic;

namespace UseDeptorygen.Samples.ResolveByCapture
{
	internal partial class Factory : IFactory
		, IDisposable
	{
		public ISuperFactory Super { get; }

		private SubFactory? _ResolveSubFactoryCache;

		public Factory(ISuperFactory super)
		{
			Super = super;
		}

		public ISubFactory ResolveSubFactory()
		{
			return _ResolveSubFactoryCache ??= new SubFactory(this, Super);
		}

		public void Dispose()
		{
		}
	}
}