// <autogenerated />
using System;
using System.Collections.Generic;

namespace UseDeptorygen.Samples.Basic
{
    internal partial class Factory : IFactory
        , IDisposable
    {
        private readonly Service _service;

        private Client? _ResolveClientCache;

        public Factory(Service service)
        {
            _service = service;
        }

        public Client ResolveClient()
        {
            return _ResolveClientCache ??= new Client(_service);
        }

        public void Dispose()
        {
        }
    }
}