// <autogenerated />
#nullable enable
using System;
using System.Collections.Generic;

namespace UseDeptorygen.Samples.Parameterize
{
	internal partial class Factory : IFactory
		, IDisposable
	{
		private Service? _ResolveServiceCache;
		private Client? _ResolveClientCache;

		public Factory()
		{
		}

		public Service ResolveService()
		{
			return _ResolveServiceCache ??= new Service();
		}

		public Client ResolveClient(Int32 repeat)
		{
			return _ResolveClientCache ??= new Client(ResolveService(), repeat);
		}

		public void Dispose()
		{
		}
	}
}