// <autogenerated />
using System;

namespace Deprovgen.Try
{
    internal partial class CapturedFactory : ICapturedFactory
    {

        private Service? _resolveServiceCache;

        public CapturedFactory()
        {
        }

        public Service ResolveService()
        {
            return _resolveServiceCache ??= new Service();
        }

        public IServiceLocator ResolveServiceLocatorAsTransient(Service2 service2)
        {
            return new ServiceLocator(service2, this);
        }
    }
}