// <autogenerated />
using System;
using Deprovgen.Try.Interface;

namespace Deprovgen.Try
{
    internal partial class ServiceLocatorFuga : IServiceLocatorFuga
    {
        private readonly Service _service;
        private readonly Service3 _service3;

        private Fuga? _resolveFugaCache;
        private Iron? _resolveIronCache;

        public ServiceLocatorFuga(Service service, Service3 service3)
        {
            _service = service;
            _service3 = service3;
        }

        public Fuga ResolveFuga()
        {
            return _resolveFugaCache ??= new Fuga(_service, _service3);
        }

        public IServiceIron ResolveIron(Service3 service3)
        {
            return _resolveIronCache ??= new Iron(service3);
        }
    }
}