// <autogenerated />
#nullable enable
using System;
using System.Collections.Generic;

namespace Deptorygen.XUnit.DataSource.UnitTests.DependencyDelegation.Source
{
	internal partial class MixinFactory : IMixinFactory
		, IDisposable
	{
		public IBaseFactory BaseFactory { get; }


		public MixinFactory(IBaseFactory baseFactory)
		{
			BaseFactory = baseFactory;
		}

		public Client ResolveClient()
		{
			return BaseFactory.ResolveClient();
		}

		public IMixinFactory ResolveMixinFactory()
		{
			return BaseFactory.ResolveMixinFactory();
		}

		public void Dispose()
		{
		}
	}
}