// <autogenerated />
using System;
using System.Collections.Generic;

namespace UseDeptorygen.Samples.UseCache
{
	internal partial class Factory : IFactory
		, IDisposable
	{
		private Service? _ResolveServiceCache;
		private Client? _ResolveClientCache;

		public Factory()
		{
		}

		public Service ResolveService()
		{
			return _ResolveServiceCache ??= new Service();
		}

		public Client ResolveClient()
		{
			return _ResolveClientCache ??= new Client(ResolveService(), ResolveService());
		}

		public void Dispose()
		{
		}
	}
}