// <autogenerated />
#nullable enable
using System;
using System.Collections.Generic;

namespace Deptorygen.XUnit.DataSource.UnitTests.CleanSelfDependency.Source
{
	internal partial class Factory : IFactory
		, IDisposable
	{

		public Factory()
		{
		}

		public Service1 ResolveService1AsTransient()
		{
			return new Service1();
		}

		public IFactory ResolveFactoryAsTransient()
		{
			return new Factory();
		}

		public void Dispose()
		{
		}
	}
}