// <autogenerated />
using System;
using System.Collections.Generic;

namespace Deptorygen.Try
{
    internal partial class CaptureFactory : ICaptureFactory
        , IDisposable
    {
        public IFactory BaseFactory { get; }

        private Client? _ResolveClientCache;

        public CaptureFactory(IFactory baseFactory)
        {
            BaseFactory = baseFactory;
        }

        public Client ResolveClient()
        {
            return _ResolveClientCache ??= new Client(BaseFactory.ResolveService());
        }

        public void Dispose()
        {
        }
    }
}