// <autogenerated />
using System;
using System.Collections.Generic;
using Deptorygen.Try;

namespace Deprovgen.Try
{
    internal partial class PinkFactory : IPinkFactory
        , IDisposable
    {
        public IRedFactory RedFactory { get; }

        private ServiceA? _ResolveServiceACache;

        public PinkFactory(IRedFactory redFactory)
        {
            RedFactory = redFactory;
        }

        public ServiceA ResolveServiceA()
        {
            return _ResolveServiceACache ??= new ServiceA();
        }


        
        public void Dispose()
        {
            _ResolveServiceACache?.Dispose();
        }
    }
}