// <autogenerated />
using System;
using System.Collections.Generic;
using Deptorygen.Try;

namespace Deprovgen.Try
{
    internal partial class RedFactory : IRedFactory
        , IDisposable
    {

        private PinkFactory? _ResolvePinkFactoryCache;

        public RedFactory()
        {
        }

        public IPinkFactory ResolvePinkFactory()
        {
            return _ResolvePinkFactoryCache ??= new PinkFactory(this);
        }


        
        public void Dispose()
        {
            _ResolvePinkFactoryCache?.Dispose();
        }
    }
}