// <autogenerated />
#nullable enable
using System;
using System.Collections.Generic;

namespace UseDeptorygen.Samples.Mixin
{
	internal partial class BaseFactory : IBaseFactory
		, IDisposable
	{
		private Service? _ResolveServiceCache;
		private ClientA? _ResolveClientACache;

		public BaseFactory()
		{
		}

		public Service ResolveService()
		{
			return _ResolveServiceCache ??= new Service();
		}

		public ClientA ResolveClientA()
		{
			return _ResolveClientACache ??= new ClientA(ResolveService());
		}

		public void Dispose()
		{
		}
	}
}