// <autogenerated />
using System;
using System.Collections.Generic;

namespace UseDeptorygen.Samples.Mixin
{
	internal partial class MixinFactory : IMixinFactory
		, IDisposable
	{
		private Service2? _ResolveService2Cache;
		private ClientB? _ResolveClientBCache;
		private Service? _ResolveServiceCache;
		private ClientA? _ResolveClientACache;

		public MixinFactory()
		{
		}

		public Service2 ResolveService2()
		{
			return _ResolveService2Cache ??= new Service2();
		}

		public ClientB ResolveClientB()
		{
			return _ResolveClientBCache ??= new ClientB(ResolveService2());
		}

		public Service ResolveService()
		{
			return _ResolveServiceCache ??= new Service();
		}

		public ClientA ResolveClientA()
		{
			return _ResolveClientACache ??= new ClientA(ResolveService());
		}

		public void Dispose()
		{
		}
	}
}